### ISSUE TITLE
Handling large amounts of CloudWatch Logs in toHaveLog()

### ISSUE THREAD

**Issue by abbyhuisman-rw** [erezrokah/aws-testing-library#29]
**Is your feature request related to a problem? Please describe.**
We've been noticing our tests fail as the CloudWatch log streams grow and it is largely due to the AWS SDK returning multiple pages of CloudWatch Logs. 

**Describe the solution you'd like**
At RobustWealth, we've added a wrapper around the SDK to page the logs along with giving a start and end date to retrieve a smaller subset of logs. Instead of rolling our own solution we would like to add this feature into this library and we'd be willing to contribute back our solution. 

**Describe alternatives you've considered**
We've considered deleting our logs, this fixed our issues but then we lose the information we need to properly monitor our applications.

**Comment by erezrokah** [comment]
@abbyhuisman-rw thanks for opening this issue.
I'd be happy to port your solution to this library (I'm gladly accepting pull requests).
I'll go over the logs sdk as well :)

**Comment by erezrokah** [comment]
@abbyhuisman-rw I've looked at the library's code and I'm already limiting the results to 1 so I'm not sure I'll get into the pagination issue.
It does makes sense to me to filter by `startTime` in regards with testing (no point in looking to far back).
I've made a pull requests for it https://github.com/erezrokah/aws-testing-library/pull/31/files

Please let me know if it makes sense to you too :)

**Comment by abbyhuisman-rw** [comment]
@erezrokah Thanks for making that change. Our internal change looks almost exactly like your code so  I think this PR will allow us to remove our home-grown solution. I didn't notice the limit one so hopefully that in tandem with the start time will fix our issue. Any idea when you would do a formal release of this code?

**Comment by erezrokah** [comment]
Thanks that’s great. I’m AFK, but I’ll do a formal release tomorrow and update (and close the issue) once I do.
Again, I appreciate the feedback :)

**Comment by erezrokah** [comment]
@abbyhuisman-rw Formal release `v1.0.1` is out :
https://github.com/erezrokah/aws-testing-library/releases/tag/v1.0.2
https://www.npmjs.com/package/aws-testing-library/v/1.0.2

**Comment by erezrokah** [comment]
Note:
I've also updated the cicd process to allow me to release versions to npm faster (just by pushing a git tag, or creating a release on GitHub): https://github.com/erezrokah/aws-testing-library/pull/33
