### ISSUE TITLE
Explicit LogGroupName in toHaveLog() function

### ISSUE THREAD

**Issue by serverlesspolska** [erezrokah/aws-testing-library#348]
**Is your feature request related to a problem? Please describe.**
It's not a problem but a feature request. 

I'd like to test code that sends events to EventBus. I have a rule that logs all events sent to my Event Bus to Cloud Watch Logs. Since recent API Destinations announcement, not every event on the EventBus will trigger Lambda function. Therefore there no function to create logs in Cloud Watch.

**Describe the solution you'd like**
I want to provide CloudWatch Log Group name instead Lambda function name in the config object:
```
expect.assertions(1); // makes sure the assertion was called
await expect({
  region: 'us-east-1',
  logGroupName: 'logGroupName',
  startTime: 0 /* optional (millis since epoch in UTC, defaults to now-1 hour) */,
  timeout: 0 /* optional (defaults to 2500) */,
  pollEvery: 0 /* optional (defaults to 500) */,
}).toHaveLog(
  'some message written to log by the lambda' /* a pattern to match against log messages */,
);
```
the rest of behavior stays the same.

**Additional context**
This request i mo

**Comment by erezrokah** [comment]
Hi @serverlesspolska, thanks for opening the issue - it makes a lot of sense to be able to configure the log group name.
It should be straightforward to implement https://github.com/erezrokah/aws-testing-library/blob/3b80743202a868f7a6c0e208d4cf49b3bd871750/src/utils/cloudwatch.ts#L12

I'll try to have a look this week

**Comment by serverlesspolska** [comment]
Thank you Erez. I will test it after you release it :-)

**Comment by serverlesspolska** [comment]
Any progress on this @erezrokah ?
