### ISSUE TITLE
Documentation question: is expect.assertions call needed for Jest extension?

### ISSUE THREAD

**Issue by paulswail** [erezrokah/aws-testing-library#378]
The README for the Jest extension includes this line for each example:
```ts
expect.assertions(1); // makes sure the assertion was called
``` 

Under what scenario would the assertion not be called (and thus result in an incorrectly passing test)? What is the risk of not including it in my test case?
If the async call to the AWS SDK fails, I imagine an exception is thrown which would be bubbled up and cause the test to fail anyway.

**Comment by erezrokah** [comment]
Hi @paulswail!

Great point, I think I took it from [here](https://jestjs.io/docs/tutorial-async#error-handling) and it's mostly useful from you expect a failure (and slightly useful to make sure you don't forget to `await`).

I believe we can remove it.

**Comment by paulswail** [comment]
Thanks @erezrokah 😃
