### ISSUE TITLE
v1.1.0 release missing lib directory contents

### ISSUE THREAD

**Issue by tclindner** [erezrokah/aws-testing-library#77]
**Describe the bug**
v1.1.0 release only contains the `LICENSE`, `package.json`, and `README.md` file. 

**To Reproduce**
1. Run `npm i aws-testing-library`
2. Inspect `node_modules` directory for contents

**Expected behavior**
`lib` directory is present with build artifact from TypeScript build.

**Screenshots**
![image](https://user-images.githubusercontent.com/5178550/73943274-1615da00-48b6-11ea-84a9-effbd23d5e0e.png)

**P.S.**
Thank you for all of your hard work on this library. It is awesome! 🎉

**Comment by erezrokah** [comment]
Sorry @tclindner, I've been try a new way to publish. I'll fix it soon

**Comment by tclindner** [comment]
No worries at all! I'm happy to help validate when you are ready (no rush at all). Let me know when you would like me to test. Thank you again 🙌

**Comment by erezrokah** [comment]
Should be fixed with `v1.1.1`

**Comment by tclindner** [comment]
Thank you, @erezrokah!! It works perfectly 🥇 🎉
